### ISSUE TITLE
mysterious list index out of range error

### ISSUE THREAD

**Issue by cheberling** [peterjc/galaxy_blast#110]
This script was working for me before, but now all of a sudden I have this error for each query:

Traceback (most recent call last):
  File "/nfs/vedanta/vbi_san1/repos/jasonnorman/blast_rbh.py", line 317, in <module>
    best_b_vs_a = dict(best_hits(b_vs_a, self_comparison))
  File "/nfs/vedanta/vbi_san1/repos/jasonnorman/blast_rbh.py", line 189, in best_hits
    length = int(parts[c_length])
IndexError: list index out of range

Is there something wrong with my input?  Does it require fasta files with a single line per seq rather than multiple lines?  Not sure what the issue is.

**Comment by cheberling** [comment]
Using blast+ version 2.7.1

See attached for example fasta file.  I am trying to run on a reduced virulence factor database specific to genus Fusobacterium.  I was also trying to run non-Fusobacterium species and thought perhaps the index out of range error was due to not having any hits, but I see the same error with the attached (which I had run successfully several months ago).

**Comment by peterjc** [comment]
I've got the hybrid assembly FAA file by email (about 3.5 thousand protein sequences), but what are you doing with it? Self comparisons - or against a second file? e.g.

```
$ ~/repositories/galaxy_blast/tools/blast_rbh/blast_rbh.py assembly.faa assembly.faa -o self.tsv -t blastp -a prot
```

**Comment by cheberling** [comment]
I’m comparing against this attached file.  However, I just noticed that this one has spaces between each fasta entry.  Could that be causing the error?

**Comment by cheberling** [comment]
I am doing directly via command line.  After downloading latest release of the software I am now getting correct results.  Do you still want me to email you the older version?  I have what I want now.

**Comment by peterjc** [comment]
I'm curious what was going wrong with the older script (eg has it been edited accidentally, or did I have a bug). If you have the broken script still, could you email it to me? Thanks.

Still, given it works with the latest version, we could just close this issue.

**Comment by cheberling** [comment]
See attached.  I changed the parentheses for the ‘print’ command so it would work with python3, but that’s it.  Any other changes must have come beforehand.

**Comment by peterjc** [comment]
Python 3 style print functions vs statements wouldn't be the problem here - you can see where I did that in e03b3d1afe99ff120e73e9cfc25a1cf0a2ab998e

I know you said you were using blast+ version 2.7.1, but sometimes jobs on the cluster don't use the same environment as your log in terminal. Is it possible you were sometimes running against an older version of BLAST+ which would ignore requests for unknown columns - resulting is less columns than expected in the output? See f71f476853e32b498e1a58b2fe6e874c4b03b44c which would give a clear error message in this case rather than an ``IndexError`` when trying to access the missing columns.

It looks like your email system removed the attachment - you might have to rename it to a ``.txt`` file or something like that to trick it. I'll close the issue for now since the latest script is working for you (but we can reopen it if some new information comes to light).

**Comment by cheberling** [comment]
Apologies, see attached as .txt file.

**Comment by peterjc** [comment]
I meant to close this as per the discussion above, doing so now
